apiVersion: apps/v1
kind: Deployment
metadata:
  name: standalone
spec:
  selector:
    matchLabels:
      app: standalone
  replicas: 1
  template:
    metadata:
      labels:
        app: standalone
        tier: mysql
    spec:
      containers:
        - name: standalone
          image: willmenn/standalone:0.9.24
          ports:
            - containerPort: 5555
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8"
        - image: mysql:5.5
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_DATABASE
              value: "auth"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "root"
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
